services:
  mosaic-dev:
    image: ghcr.io/osgeo/gdal:ubuntu-small-3.10.2
    entrypoint: [ sleep, infinity ]
    volumes:
      - ./fim_mosaicker:/app
      - ./test:/app/test
    environment:
      - CPLUS_INCLUDE_PATH=/usr/include/gdal
      - C_INCLUDE_PATH=/usr/include/gdal
      - VIRTUAL_ENV=/opt/venv
      - PATH=/opt/venv/bin:$PATH

  inundate-dev:
    build: .
    entrypoint: [ sleep, infinity ]
    volumes:
      - ./hand_inundator:/app
      - ./test:/app/test
    # environment:
    #   - CPLUS_INCLUDE_PATH=/usr/include/gdal
    #   - C_INCLUDE_PATH=/usr/include/gdal
    #   - VIRTUAL_ENV=/opt/venv
    #   - PATH=/opt/venv/bin:$PATH


    # inundate-test:
    #   build: .
    #   entrypoint: []
    #   command: ['python', '-m', 'unittest', 'test.test_inundate']
    #   volumes:
    #     - .:/app
    #     - ~/.aws:/root/.aws:ro
    #   environment:
    #     - CPLUS_INCLUDE_PATH=/usr/include/gdal
    #     - C_INCLUDE_PATH=/usr/include/gdal
    #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #     - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    #     - VIRTUAL_ENV=/opt/venv
    #     - PATH=/opt/venv/bin:$PATH
