version: '3.8'
services:
  mosaic-test:
    build: .
    command: ['python', '-m', 'unittest', 'test.test_mosaic']
    volumes:
      - .:/app
    environment:
      - CPLUS_INCLUDE_PATH=/usr/include/gdal
      - C_INCLUDE_PATH=/usr/include/gdal
